load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "error_lib",
    hdrs = glob(["**/*.h"]),
    includes = [
        ".",
        "..",
    ],
    visibility = ["//visibility:public"],
)
